<?php

namespace Tests\Unit\Models;

use App\Models\Course;
use App\Models\Lesson;
use App\Models\Question;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

class LessonTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    protected $lesson;
    protected $question;
    protected $course;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->course = factory(Course::class)->create();
        $this->lesson = factory(Lesson::class)->create([
            'course_id' => $this->course->id,
        ]);
        $this->question = factory(Question::class)->create([
            'lesson_id' => $this->lesson->id,
        ]);
    }

    /**
     * Test table has columns.
     *
     * @return void
     */
    public function test_lessons_table_has_expected_columns()
    {
        $this->assertTrue(
            Schema::hasColumns('lessons', [
                'id',
                'course_id',
                'name',
            ]),
            1
        );
    }

    /**
     * Test Lesson mass assignment properties.
     *
     * @return void
     */
    public function test_contains_valid_fillable_properties()
    {
        $this->assertEquals([
            'name',
            'course_id',
        ], $this->lesson->getFillable());
    }

    public function test_lesson_has_many_questions()
    {
        $lesson = $this->lesson;
        $question = $this->question;

        $this->assertTrue($lesson->questions->contains($question));
        $this->assertInstanceOf(Collection::class, $lesson->questions);
    }

    public function test_lesson_belongs_to_course()
    {
        $lesson = $this->lesson;

        $this->assertEquals(1, $lesson->course->count());
        $this->assertInstanceOf(Course::class, $lesson->course);
    }

    public function test_lesson_belongs_to_many_users()
    {
        $lesson = $this->lesson;

        $this->assertInstanceOf(Collection::class, $lesson->users);
    }
}
